const express = require("express")
const { handleGameDelete,handleGamePost,handleGameGet,handleGameCreate,getGameInfo,joinGame,handleGameStats, getWord} = require("../controllers/game")
const router = express.Router()
router.route('/')
    .post(handleGamePost)
    .get(getGameInfo)
    .delete(handleGameDelete)
router.route('/create')
    .post(handleGameCreate)
router.route('/join')
    .get(joinGame)
router.route("/current/:id")
    .get(handleGameGet)
router.route("/user")
    .get(handleGameStats)
router.route("/UserWord")
    .get(getWord)
module.exports = router;